cluster.name: cloud-tmp
node.name: elasticsearch-tmp
network.host: 10.52.173.140
node.master: true
node.data: true
discovery.seed_hosts: ["10.52.173.140:9300"]
cluster.initial_master_nodes: ["elasticsearch-0","elasticsearch-1","elasticsearch-2"]

xpack.security.enabled: false
xpack.security.transport.ssl.enabled: false